--- Løpende data brukt direkte til tester ---
-- Basert på rader fra Arena-q2, syntetiske data

Insert into PERSON (PERSON_ID, FODSELSDATO, STATUS_DNR, PERSONNR, FODSELSNR, ETTERNAVN, FORNAVN, DATO_FRA,
                    STATUS_SAMTYKKE, DATO_SAMTYKKE, VERNEPLIKTKODE, MAALFORM, LANDKODE_STATSBORGER, KONTONUMMER,
                    STATUS_BILDISP, FORMIDLINGSGRUPPEKODE, VIKARGRUPPEKODE, KVALIFISERINGSGRUPPEKODE,
                    RETTIGHETSGRUPPEKODE, REG_DATO, REG_USER, MOD_DATO, MOD_USER, AETATORGENHET, LONNSLIPP_EPOST,
                    DATO_OVERFORT_AMELDING, DATO_SIST_INAKTIV, BEGRUNNELSE_FORMIDLINGSGRUPPE, HOVEDMAALKODE,
                    BRUKERID_NAV_KONTAKT, FR_KODE, ER_DOED, PERSON_ID_STATUS, SPERRET_KOMMENTAR, SPERRET_TIL,
                    SPERRET_DATO, SPERRET_AV)
values (4873545, DATE '1969-01-27', 'N', 44836, '12312312312', 'BADEBY', 'HISTORISK',
        DATE '2025-03-27', 'J', DATE '2025-03-27', null, 'NO', 'NO', null, null,
        'ISERV', 'IVIK', 'IVURD', 'IYT', DATE '2025-03-27', 'MSF4402',
        DATE '2025-09-23', 'MSF4402', '1580', null, null, null, null, null, null, null, null, 'AKTIV',
        null, null, null, null);


Insert into SAK (SAK_ID, SAKSKODE, REG_DATO, REG_USER, MOD_DATO, MOD_USER, TABELLNAVNALIAS, OBJEKT_ID, AAR, LOPENRSAK,
                 DATO_AVSLUTTET, SAKSTATUSKODE, ARKIVNOKKEL, AETATENHET_ARKIV, ARKIVHENVISNING, BRUKERID_ANSVARLIG,
                 AETATENHET_ANSVARLIG, OBJEKT_KODE, STATUS_ENDRET, PARTISJON, ER_UTLAND)
values (13489616, 'AA', DATE '2025-03-27', 'MSF4402', DATE '2025-03-27', 'MSF4402B',
        'PERS', 4873545, 2025, 6162, null, 'INAKT', null, '4402', null, 'MSF4402', '4402', null,
        DATE '2025-03-27', null, 'N');

Insert into VEDTAK (VEDTAK_ID, SAK_ID, VEDTAKSTATUSKODE, VEDTAKTYPEKODE, REG_DATO, REG_USER, MOD_DATO, MOD_USER,
                    UTFALLKODE, BEGRUNNELSE, BRUKERID_ANSVARLIG, AETATENHET_BEHANDLER, AAR, LOPENRSAK, LOPENRVEDTAK,
                    RETTIGHETKODE, AKTFASEKODE, BREV_ID, TOTALBELOP, DATO_MOTTATT, VEDTAK_ID_RELATERT,
                    AVSNITTLISTEKODE_VALGT, PERSON_ID, BRUKERID_BESLUTTER, STATUS_SENSITIV, VEDLEGG_BETPLAN, PARTISJON,
                    OPPSUMMERING_SB2, DATO_UTFORT_DEL1, DATO_UTFORT_DEL2, OVERFORT_NAVI, FRA_DATO, TIL_DATO,
                    SF_OPPFOLGING_ID, STATUS_SOSIALDATA, KONTOR_SOSIALDATA, TEKSTVARIANTKODE, VALGT_BESLUTTER,
                    TEKNISK_VEDTAK, DATO_INNSTILT, ER_UTLAND)
values (37067849, 13489616, 'IVERK', 'O', DATE '2022-03-28', 'MSF4402',
        DATE '2025-05-21', 'MSF4402B', 'JA', 'test', 'MSF4402', '4402', 2025, 6162, 1, 'AAP', 'IKKE',
        31092790, null, DATE '2022-03-28', null, null, 4873545, 'MSF4402B', null, null, null, null,
        null, null, null, DATE '2022-08-30', DATE '2023-08-30', null, 'N', null, null, 'MSF4402B', null,
        DATE '2025-03-28', 'N');

Insert into VEDTAKFAKTA (VEDTAK_ID, VEDTAKFAKTAKODE, VEDTAKVERDI, REG_DATO, REG_USER, MOD_DATO, MOD_USER, PERSON_ID,
                         PARTISJON)
values (37067849, 'DAGS', '255', DATE '2025-03-28', 'MSF4402',
        DATE '2025-03-28', 'MSF4402', null, null);

Insert into BEREGNINGSLEDD(BEREGNINGSLEDD_ID, VERDI, PERSON_ID, BEREGNINGSLEDDKODE, DATO_FRA, TABELLNAVNALIAS_KILDE)
values
       (111, 7460, 4873545, 'AAP', DATE '2010-01-01', 'KVOTBR'),
       (121, 460, 4873545, 'MAAPU', DATE '2010-01-01', 'KVOTBR');
